# Make sure to compose up this .yml on docker
# go to localhost:8080 on browser
# Use root as user
# Use examplepass as password
#use docker container ls to find ip when database container is running, then docker inspect "database name"


version: '3.1'

services:
  db:
    image: mysql
    container_name: database
    volumes:
      - db-data:/mySQL/data
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
  phpMyAdmin:
    image: phpmyadmin
    environment: 
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

volumes:
  db-data:

#running bash: docker exec -it database bash
#example mysql query
#mysql -u root -p examplepass -D mydatabase -e "SELECT * FROM firstTable"
#echo "SELECT * FROM firstTable" | mysql --user=root --password=examplepass mydatabase
#