version: '3'

services:
  mqtt-broker: # The mqtt broker container
    image: eclipse-mosquitto
    ports:
      - "1883:1883" # Maps port 1883 inside container to 1883 on local host
  
  simsensor1: # The first simulated sensor container
    build: .
    depends_on:
      - mqtt-broker
    command: python3 simsensor.py

  simsensor2: # The second simulated sensor container
    build: .
    depends_on:
      - mqtt-broker
    command: python3 simsensor.py

  simsensor3: # The third simulated sensor container
    build: .
    depends_on:
      - mqtt-broker
    command: python3 simsensor.py
